# Theme activation (minimal mistakes use the Gemfile)
layout: page
plugins: [jekyll-include-cache]
remote_theme: "mmistakes/minimal-mistakes@4.21.0"

# global conf
title: "QuatroPe"
description: "QuatroPe is a non for profit organization devoted to create quality software"
logo: https://avatars3.githubusercontent.com/u/53583309?s=400&u=161d7aa2618b0fdbda77945ea4ebbcc7109f3ebb&v=4

# full configuration: https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
minimal_mistakes_skin : "aqua" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
